<?php
/**
 * The throwaway RSA key pair the JWT tests sign and verify with.
 *
 * @package GaTelegramBridge
 */

declare( strict_types=1 );

namespace GaTelegramBridge\Tests;

/**
 * One 2048-bit key pair per test run, generated by the bootstrap.
 *
 * A real service-account key is never committed and never used in tests
 * (docs/TESTING.md → Fixtures); the signatures asserted here are made with this
 * pair and verified against its own public half.
 */
final class TestKey {

	/**
	 * The private half, PEM encoded.
	 *
	 * @var string
	 */
	private static string $private_pem = '';

	/**
	 * The public half, PEM encoded.
	 *
	 * @var string
	 */
	private static string $public_pem = '';

	/**
	 * Generates the pair. Called once from tests/bootstrap.php.
	 *
	 * @throws \RuntimeException When this PHP cannot generate or read an RSA key.
	 */
	public static function generate(): void {
		if ( '' !== self::$private_pem ) {
			return;
		}

		$pair = openssl_pkey_new(
			array(
				'private_key_bits' => 2048,
				'private_key_type' => OPENSSL_KEYTYPE_RSA,
			)
		);

		if ( false === $pair ) {
			throw new \RuntimeException( 'Could not generate the throwaway RSA key pair for the tests.' );
		}

		$private_pem = '';
		openssl_pkey_export( $pair, $private_pem );

		$details = openssl_pkey_get_details( $pair );

		if ( ! is_array( $details ) || ! isset( $details['key'] ) || ! is_string( $details['key'] ) ) {
			throw new \RuntimeException( 'Could not read the public half of the throwaway RSA key pair.' );
		}

		self::$private_pem = $private_pem;
		self::$public_pem  = $details['key'];
	}

	/**
	 * Returns the private half, as a service-account key file carries it.
	 */
	public static function private_pem(): string {
		self::generate();

		return self::$private_pem;
	}

	/**
	 * Returns the public half, for openssl_verify().
	 */
	public static function public_pem(): string {
		self::generate();

		return self::$public_pem;
	}

	/**
	 * Returns a service-account key file built around the throwaway key.
	 *
	 * @param array<string, string> $overrides Fields to use instead of the defaults.
	 * @return array{client_email: string, private_key: string, token_uri: string}
	 */
	public static function service_account( array $overrides = array() ): array {
		return array(
			'client_email' => $overrides['client_email'] ?? 'reporter@example.iam.gserviceaccount.com',
			'private_key'  => $overrides['private_key'] ?? self::private_pem(),
			'token_uri'    => $overrides['token_uri'] ?? 'https://oauth2.googleapis.com/token',
		);
	}
}
