#!/usr/bin/env bash

## Description: Import Database WordPress
## Usage: wp-db-import
## Example: "ddev wp-db-import"

set -e

ddev import-db --file=mysql.sql
ddev wp search-replace 'https://dovira.vet/' 'https://dovira.ddev.site' --all-tables
ddev wp user create local-administrator local-administrator@dovira.ddev.site --role=administrator --user_pass=password
