<?php
return [
	'taxonomy'    => 'service-city',
	'object_type' => ['service', 'employee', 'vacancy'],
	'args'        => [
		'label'                 => __( 'City', 'dovira' ),
		'labels'                => [
			'name'              => __( 'City', 'dovira' ),
			'singular_name'     => __( 'City', 'dovira' ),
			'search_items'      => __( 'Search Cities', 'dovira' ),
			'all_items'         => __( 'All Cities', 'dovira' ),
			'view_item '        => __( 'View City', 'dovira' ),
			'parent_item'       => __( 'Parent City', 'dovira' ),
			'parent_item_colon' => __( 'Parent City:', 'dovira' ),
			'edit_item'         => __( 'Edit City', 'dovira' ),
			'update_item'       => __( 'Update City', 'dovira' ),
			'add_new_item'      => __( 'Add new City', 'dovira' ),
			'new_item_name'     => __( 'New City name', 'dovira' ),
			'menu_name'         => __( 'Cities', 'dovira' ),
		],
		'description'           => '',
		'public'                => true,
		'publicly_queryable'    => true,
		'show_in_nav_menus'     => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'show_tagcloud'         => true,
		'show_in_rest'          => true,
		'hierarchical'          => true,
		'update_count_callback' => '',
		'rewrite'               => true,
		'capabilities'          => [],
		'meta_box_cb'           => null,
		'show_admin_column'     => true,
		'show_in_quick_edit'    => true,
		'_builtin'              => false,
	],
];
