<?php

return [
	'post_type' => 'employee',
	'args'      => [
		'label'               => __( 'Employee', 'dovira' ),
		'labels'              => [
			'name'                  => __( 'Employee', 'dovira' ),
			'singular_name'         => __( 'Employee', 'dovira' ),
			'add_new'               => __( 'Add Employee', 'dovira' ),
			'add_new_item'          => __( 'Add new Employee', 'dovira' ),
			'edit_item'             => __( 'Edit Employee', 'dovira' ),
			'new_item'              => __( 'New Employee', 'dovira' ),
			'view_item'             => __( 'View Employee', 'dovira' ),
			'search_items'          => __( 'Search Employees', 'dovira' ),
			'not_found'             => __( 'Employees not found', 'dovira' ),
			'not_found_in_trash'    => __( 'Employees not found in trash', 'dovira' ),
			'parent_item_colon'     => __( 'Parent Employee:', 'dovira' ),
			'menu_name'             => __( 'Employees', 'dovira' ),
			'all_items'             => __( 'All Employees', 'dovira' ),
			'archives'              => __( 'Employee archives', 'dovira' ),
			'insert_into_item'      => __( 'Insert into Employee', 'dovira' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Employee', 'dovira' ),
			'featured_image'        => __( 'Employee Featured image', 'dovira' ),
			'set_featured_image'    => __( 'Set Employee Featured image', 'dovira' ),
			'remove_featured_image' => __( 'Remove Employee Featured image', 'dovira' ),
			'use_featured_image'    => __( 'Use Employee Featured image', 'dovira' ),
			'filter_items_list'     => __( 'Filter Employees list', 'dovira' ),
			'items_list_navigation' => __( 'Employees list navigation', 'dovira' ),
			'items_list'            => __( 'Employees list', 'dovira' ),
			'name_admin_bar'        => __( 'Employee', 'dovira' ),
			'view_items'            => __( 'View Employees', 'dovira' ),
			'attributes'            => __( 'Attributes', 'dovira' ),
		],
		'description'         => '',
		'public'              => true,
		'publicly_queryable'  => true,
		'exclude_from_search' => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'show_in_rest'        => true,
		'menu_position'       => 100,
		'menu_icon'           => 'dashicons-groups',
		'capability_type'     => 'page',
		'map_meta_cap'        => true,
		'hierarchical'        => false,
		'taxonomies'          => [],
		'has_archive'         => false,
		'rewrite'             => [
			'slug' => 'team',
			'with_front' => false,
		],
		'query_var'           => true,
		'can_export'          => true,
	],
];
