<?php

return [
	'post_type' => 'questionary',
	'args'      => [
		'label'               => __( 'Questionary', 'dovira' ),
		'labels'              => [
			'name'                  => __( 'Questionaries', 'dovira' ),
			'singular_name'         => __( 'Questionary', 'dovira' ),
			'add_new'               => __( 'Add Questionary', 'dovira' ),
			'add_new_item'          => __( 'Add new Questionary', 'dovira' ),
			'edit_item'             => __( 'Edit Questionary', 'dovira' ),
			'new_item'              => __( 'New Questionary', 'dovira' ),
			'view_item'             => __( 'View Questionary', 'dovira' ),
			'search_items'          => __( 'Search Questionaries', 'dovira' ),
			'not_found'             => __( 'Questionaries not found', 'dovira' ),
			'not_found_in_trash'    => __( 'Questionaries not found in trash', 'dovira' ),
			'parent_item_colon'     => __( 'Parent Questionary:', 'dovira' ),
			'menu_name'             => __( 'Questionaries', 'dovira' ),
			'all_items'             => __( 'All Questionaries', 'dovira' ),
			'archives'              => __( 'Questionary archives', 'dovira' ),
			'insert_into_item'      => __( 'Insert into Questionary', 'dovira' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Questionary', 'dovira' ),
			'featured_image'        => __( 'Questionary Featured image', 'dovira' ),
			'set_featured_image'    => __( 'Set Questionary Featured image', 'dovira' ),
			'remove_featured_image' => __( 'Remove Questionary Featured image', 'dovira' ),
			'use_featured_image'    => __( 'Use Questionary Featured image', 'dovira' ),
			'filter_items_list'     => __( 'Filter Questionaries list', 'dovira' ),
			'items_list_navigation' => __( 'Questionaries list navigation', 'dovira' ),
			'items_list'            => __( 'Questionaries list', 'dovira' ),
			'name_admin_bar'        => __( 'Questionary', 'dovira' ),
			'view_items'            => __( 'View Questionaries', 'dovira' ),
			'attributes'            => __( 'Attributes', 'dovira' ),
		],
		'description'         => '',
		'public'              => false,
		'publicly_queryable'  => false,
		'exclude_from_search' => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => false,
		'show_in_rest'        => true,
		'menu_position'       => 100,
		'menu_icon'           => 'dashicons-editor-help',
		'capability_type'     => 'conversation',
		'capabilities'        => [
			'edit_post'              => 'edit_conversation',
			'read_post'              => 'read_conversation',
			'delete_post'            => 'delete_conversation',
			'edit_posts'             => 'edit_conversations',
			'edit_others_posts'      => 'edit_others_conversations',
			'publish_posts'          => 'publish_conversations',
			'read_private_posts'     => 'read_private_conversations',
			'delete_posts'           => 'delete_conversations',
			'delete_private_posts'   => 'delete_private_conversations',
			'delete_published_posts' => 'delete_published_conversations',
			'delete_others_posts'    => 'delete_others_conversations',
			'edit_private_posts'     => 'edit_private_conversations',
			'edit_published_posts'   => 'edit_published_conversations',
		],
		'map_meta_cap'        => true,
		'hierarchical'        => false,
		'taxonomies'          => [],
		'supports'            => [ 'title' ],
		'has_archive'         => false,
		'rewrite'             => false,
		'query_var'           => true,
		'can_export'          => true,
	],
];
