<?php

return [
	'post_type' => 'service',
	'args'      => [
		'label'               => __( 'Service', 'dovira' ),
		'labels'              => [
			'name'                  => __( 'Service', 'dovira' ),
			'singular_name'         => __( 'Service', 'dovira' ),
			'add_new'               => __( 'Add Service', 'dovira' ),
			'add_new_item'          => __( 'Add new Service', 'dovira' ),
			'edit_item'             => __( 'Edit Service', 'dovira' ),
			'new_item'              => __( 'New Service', 'dovira' ),
			'view_item'             => __( 'View Service', 'dovira' ),
			'search_items'          => __( 'Search Services', 'dovira' ),
			'not_found'             => __( 'Services not found', 'dovira' ),
			'not_found_in_trash'    => __( 'Services not found in trash', 'dovira' ),
			'parent_item_colon'     => __( 'Parent Service:', 'dovira' ),
			'menu_name'             => __( 'Services', 'dovira' ),
			'all_items'             => __( 'All Services', 'dovira' ),
			'archives'              => __( 'Service archives', 'dovira' ),
			'insert_into_item'      => __( 'Insert into Service', 'dovira' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Service', 'dovira' ),
			'featured_image'        => __( 'Service Featured image', 'dovira' ),
			'set_featured_image'    => __( 'Set Service Featured image', 'dovira' ),
			'remove_featured_image' => __( 'Remove Service Featured image', 'dovira' ),
			'use_featured_image'    => __( 'Use Service Featured image', 'dovira' ),
			'filter_items_list'     => __( 'Filter Services list', 'dovira' ),
			'items_list_navigation' => __( 'Services list navigation', 'dovira' ),
			'items_list'            => __( 'Services list', 'dovira' ),
			'name_admin_bar'        => __( 'Service', 'dovira' ),
			'view_items'            => __( 'View Services', 'dovira' ),
			'attributes'            => __( 'Attributes', 'dovira' ),
		],
		'description'         => '',
		'public'              => true,
		'publicly_queryable'  => true,
		'exclude_from_search' => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'show_in_rest'        => true,
		'menu_position'       => 100,
		'menu_icon'           => 'dashicons-open-folder',
		'capability_type'     => 'page',
		'map_meta_cap'        => true,
		'hierarchical'        => true,
		'taxonomies'          => [],
		'supports'            => [ 'title', 'editor', 'page-attributes' ],
		'has_archive'         => false,
		'rewrite'             => [
			'slug'       => 'services',
			'with_front' => false,
		],
		'query_var'           => true,
		'can_export'          => true,
	],
];
