<?php

return [
	'post_type' => 'vacancy',
	'args'      => [
		'label'               => __( 'Vacancy', 'dovira' ),
		'labels'              => [
			'name'                  => __( 'Vacancy', 'dovira' ),
			'singular_name'         => __( 'Vacancy', 'dovira' ),
			'add_new'               => __( 'Add Vacancy', 'dovira' ),
			'add_new_item'          => __( 'Add new Vacancy', 'dovira' ),
			'edit_item'             => __( 'Edit Vacancy', 'dovira' ),
			'new_item'              => __( 'New Vacancy', 'dovira' ),
			'view_item'             => __( 'View Vacancy', 'dovira' ),
			'search_items'          => __( 'Search Vacancies', 'dovira' ),
			'not_found'             => __( 'Vacancies not found', 'dovira' ),
			'not_found_in_trash'    => __( 'Vacancies not found in trash', 'dovira' ),
			'parent_item_colon'     => __( 'Parent Vacancy:', 'dovira' ),
			'menu_name'             => __( 'Vacancies', 'dovira' ),
			'all_items'             => __( 'All Vacancies', 'dovira' ),
			'archives'              => __( 'Vacancy archives', 'dovira' ),
			'insert_into_item'      => __( 'Insert into Vacancy', 'dovira' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Vacancy', 'dovira' ),
			'featured_image'        => __( 'Vacancy Featured image', 'dovira' ),
			'set_featured_image'    => __( 'Set Vacancy Featured image', 'dovira' ),
			'remove_featured_image' => __( 'Remove Vacancy Featured image', 'dovira' ),
			'use_featured_image'    => __( 'Use Vacancy Featured image', 'dovira' ),
			'filter_items_list'     => __( 'Filter Vacancies list', 'dovira' ),
			'items_list_navigation' => __( 'Vacancies list navigation', 'dovira' ),
			'items_list'            => __( 'Vacancies list', 'dovira' ),
			'name_admin_bar'        => __( 'Vacancy', 'dovira' ),
			'view_items'            => __( 'View Vacancies', 'dovira' ),
			'attributes'            => __( 'Attributes', 'dovira' ),
		],
		'description'         => '',
		'public'              => true,
		'publicly_queryable'  => true,
		'exclude_from_search' => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'show_in_rest'        => true,
		'menu_position'       => 100,
		'menu_icon'           => 'dashicons-businesswoman',
		'capability_type'     => 'page',
		'map_meta_cap'        => true,
		'hierarchical'        => true,
		'taxonomies'          => ['service-city'],
		'supports'            => [ 'title', 'page-attributes' ],
		'has_archive'         => false,
		'rewrite'             => [
			'slug'       => 'vacancies',
			'with_front' => false,
		],
		'query_var'           => true,
		'can_export'          => true,
	],
];
